#!/bin/sh

case $1 in
start)
	if [ -e /var/etc/.tuxmaild ]; then
		echo "starte tuxmaild..."
		/bin/tuxmaild
		sleep 1
	fi
	;;
stop)
	if [ -e /var/etc/.tuxmaild ] && [ -e /var/run/tuxmaild.pid ]; then
		echo "stoppe tuxmaild..."
		kill $( cat /var/run/tuxmaild.pid )
		sleep 2
	fi
	;;
esac

exit 0
